networks:
  neo4j-network:
    driver: bridge

services:

  python:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - .:/workspace
    command: sleep infinity

  neo4j:
    image: bitnami/neo4j:latest
    networks:
      - neo4j-network
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=neo4j/geheim