services:

  python:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - .:/workspace
    command: sleep infinity

  neo4j:
    image: neo4j:4.4
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      - NEO4J_AUTH=neo4j/geheim